# https://hub.docker.com/r/trfore/docker-centos9-systemd
# Minimal systemd-enabled CentOS Stream 9 image
FROM trfore/docker-centos9-systemd:latest

COPY start.sh /root/start.sh

CMD ["/root/start.sh"]
