version: '3.6'

x-aliases:
  - &bbase
    context: ./
    dockerfile: Dockerfile
  - &args_debug
    php_config_args: "--enable-debug"
  - &args_valgrind
    php_config_args: "-enable-debug --with-valgrind"
  - &args_debug_zts
    php_config_args: "--enable-maintainer-zts --enable-debug"     
  - &args_zts
    php_config_args: "--enable-maintainer-zts"  

services:    
  alpine-5.4:
    build: 
      <<: *bbase
      args: &args_5_4 
        php_url: "https://secure.php.net/get/php-5.4.39.tar.bz2/from/this/mirror"
        php_version: 5.4.39
        alpine_version: 3.4
        php_sha: 7ceb76538e709c74533210ae41148d5c01c330ac8a73220954bbc4fcae69d77e
    image: datadog/docker-library:ddtrace_alpine_php-5.4
  alpine-5.5:
    build:
      <<: *bbase
      args: &args_5_5
        php_url: "https://secure.php.net/get/php-5.5.38.tar.xz/from/this/mirror"
        php_version: 5.5.38
        alpine_version: 3.4
        php_sha: 473c81ebb2e48ca468caee031762266651843d7227c18a824add9b07b9393e38
    image: datadog/docker-library:ddtrace_alpine_php-5.5
  alpine-5.6:
    build:
      <<: *bbase
      args: &args_5_6
        php_url: "https://secure.php.net/get/php-5.6.40.tar.xz/from/this/mirror"
        php_version: 5.6.40
        alpine_version: 3.4
        php_sha: 1369a51eee3995d7fbd1c5342e5cc917760e276d561595b6052b21ace2656d1c
    image: datadog/docker-library:ddtrace_alpine_php-5.6
  alpine-7.0:
    build:
      <<: *bbase
      args: &args_7_0
        php_url: "https://secure.php.net/get/php-7.0.33.tar.xz/from/this/mirror"
        php_sha: ab8c5be6e32b1f8d032909dedaaaa4bbb1a209e519abb01a52ce3914f9a13d96
        php_version: 7.0.33
    image: datadog/docker-library:ddtrace_alpine_php-7.0
  alpine-7.1:
    build:
      <<: *bbase
      args: &args_7_1
        php_url: "https://secure.php.net/get/php-7.1.21.tar.xz/from/this/mirror"
        php_version: 7.1.21
        php_sha: d4da6dc69d3fe1e6b2b80f16b262f391037bfeb21213c966e026bd45d7ca2813
    image: datadog/docker-library:ddtrace_alpine_php-7.1
  alpine-7.2:
    build:
      <<: *bbase
      args: &args_7_2
        php_url: "https://secure.php.net/get/php-7.2.9.tar.xz/from/this/mirror"
        php_version: 7.2.9
        php_sha: 3585c1222e00494efee4f5a65a8e03a1e6eca3dfb834814236ee7f02c5248ae0
    image: datadog/docker-library:ddtrace_alpine_php-7.2
  alpine-7.3:
    build:
      <<: *bbase
      args: &args_7_3
        php_url: "https://secure.php.net/get/php-7.3.2.tar.xz/from/this/mirror"
        php_version: 7.3.2
        php_sha: 010b868b4456644ae227d05ad236c8b0a1f57dc6320e7e5ad75e86c5baf0a9a8
    image: datadog/docker-library:ddtrace_alpine_php-7.3
  alpine-5.4-debug:
    depends_on: [ alpine-5.4 ]
    build: { <<: *bbase, args: { <<: *args_5_4, <<: *args_debug }}
    image: datadog/docker-library:ddtrace_alpine_php-5.4-debug
  alpine-5.4-valgrind:
    depends_on: [ alpine-5.4 ]
    build: { <<: *bbase, args: { <<: *args_5_4, <<: *args_valgrind }}
    image: datadog/docker-library:ddtrace_alpine_php-5.4-valgrind
  alpine-5.4-debug-zts:
    depends_on: [ alpine-5.4 ]
    build: { <<: *bbase, args: { <<: *args_5_4, <<: *args_debug_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-5.4-debug-zts
  alpine-5.4-zts:
    depends_on: [ alpine-5.4 ]
    build: { <<: *bbase, args: { <<: *args_5_4, <<: *args_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-5.4-zts    

  alpine-5.5-debug:
    depends_on: [ alpine-5.5 ]
    build: { <<: *bbase, args: { <<: *args_5_5, <<: *args_debug }}
    image: datadog/docker-library:ddtrace_alpine_php-5.5-debug
  alpine-5.5-valgrind:
    depends_on: [ alpine-5.5 ]
    build: { <<: *bbase, args: { <<: *args_5_5, <<: *args_valgrind }}
    image: datadog/docker-library:ddtrace_alpine_php-5.5-valgrind
  alpine-5.5-debug-zts:
    depends_on: [ alpine-5.5 ]
    build: { <<: *bbase, args: { <<: *args_5_5, <<: *args_debug_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-5.5-debug-zts
  alpine-5.5-zts:
    depends_on: [ alpine-5.5 ]
    build: { <<: *bbase, args: { <<: *args_5_5, <<: *args_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-5.5-zts    

  alpine-5.6-debug:
    depends_on: [ alpine-5.6 ]
    build: { <<: *bbase, args: { <<: *args_5_6, <<: *args_debug }}
    image: datadog/docker-library:ddtrace_alpine_php-5.6-debug
  alpine-5.6-valgrind:
    depends_on: [ alpine-5.6 ]
    build: { <<: *bbase, args: { <<: *args_5_6, <<: *args_valgrind }}
    image: datadog/docker-library:ddtrace_alpine_php-5.6-valgrind
  alpine-5.6-debug-zts:
    depends_on: [ alpine-5.6 ]
    build: { <<: *bbase, args: { <<: *args_5_6, <<: *args_debug_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-5.6-debug-zts
  alpine-5.6-zts:
    depends_on: [ alpine-5.6 ]
    build: { <<: *bbase, args: { <<: *args_5_6, <<: *args_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-5.6-zts    
    
  alpine-7.0-debug:
    depends_on: [ alpine-7.0 ]
    build: { <<: *bbase, args: { <<: *args_7_0, <<: *args_debug }}
    image: datadog/docker-library:ddtrace_alpine_php-7.0-debug
  alpine-7.0-valgrind:
    depends_on: [ alpine-7.0 ]
    build: { <<: *bbase, args: { <<: *args_7_0, <<: *args_valgrind }}
    image: datadog/docker-library:ddtrace_alpine_php-7.0-valgrind
  alpine-7.0-debug-zts:
    depends_on: [ alpine-7.0 ]
    build: { <<: *bbase, args: { <<: *args_7_0, <<: *args_debug_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-7.0-debug-zts
  alpine-7.0-zts:
    depends_on: [ alpine-7.0 ]
    build: { <<: *bbase, args: { <<: *args_7_0, <<: *args_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-7.0-zts    
    
  alpine-7.1-debug:
    depends_on: [ alpine-7.1 ]
    build: { <<: *bbase, args: { <<: *args_7_1, <<: *args_debug }}
    image: datadog/docker-library:ddtrace_alpine_php-7.1-debug
  alpine-7.1-valgrind:
    depends_on: [ alpine-7.1 ]
    build: { <<: *bbase, args: { <<: *args_7_1, <<: *args_valgrind }}
    image: datadog/docker-library:ddtrace_alpine_php-7.1-valgrind
  alpine-7.1-debug-zts:
    depends_on: [ alpine-7.1 ]
    build: { <<: *bbase, args: { <<: *args_7_1, <<: *args_debug_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-7.1-debug-zts
  alpine-7.1-zts:
    depends_on: [ alpine-7.1 ]
    build: { <<: *bbase, args: { <<: *args_7_1, <<: *args_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-7.1-zts    
    
  alpine-7.2-debug:
    depends_on: [ alpine-7.2 ]
    build: { <<: *bbase, args: { <<: *args_7_2, <<: *args_debug }}
    image: datadog/docker-library:ddtrace_alpine_php-7.2-debug
  alpine-7.2-valgrind:
    depends_on: [ alpine-7.2 ]
    build: { <<: *bbase, args: { <<: *args_7_2, <<: *args_valgrind }}
    image: datadog/docker-library:ddtrace_alpine_php-7.2-valgrind
  alpine-7.2-debug-zts:
    depends_on: [ alpine-7.2 ]
    build: { <<: *bbase, args: { <<: *args_7_2, <<: *args_debug_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-7.2-debug-zts
  alpine-7.2-zts:
    depends_on: [ alpine-7.2 ]
    build: { <<: *bbase, args: { <<: *args_7_2, <<: *args_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-7.2-zts

  alpine-7.3-debug:
    depends_on: [ alpine-7.3 ]
    build: { <<: *bbase, args: { <<: *args_7_3, <<: *args_debug }}
    image: datadog/docker-library:ddtrace_alpine_php-7.3-debug
  alpine-7.3-valgrind:
    depends_on: [ alpine-7.3 ]
    build: { <<: *bbase, args: { <<: *args_7_3, <<: *args_valgrind }}
    image: datadog/docker-library:ddtrace_alpine_php-7.3-valgrind
  alpine-7.3-debug-zts:
    depends_on: [ alpine-7.3 ]
    build: { <<: *bbase, args: { <<: *args_7_3, <<: *args_debug_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-7.3-debug-zts
  alpine-7.3-zts:
    depends_on: [ alpine-7.3 ]
    build: { <<: *bbase, args: { <<: *args_7_3, <<: *args_zts }}
    image: datadog/docker-library:ddtrace_alpine_php-7.3-zts  