FROM mcr.microsoft.com/windows/servercore:ltsc2022

RUN curl "https://go.microsoft.com/fwlink/?LinkID=866662" -L -o sqlserver-install.exe
RUN .\sqlserver-install.exe /ACTION="install" /IACCEPTSQLSERVERLICENSETERMS /QUIET /VERBOSE

CMD ping -t localhost > NUL
