FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN curl "https://download.microsoft.com/download/3/9/F/39F968FA-DEBB-4960-8F9E-0E7BB3035959/SQLEXPR_x64_ENU.exe" -L -o sqlserver-install.exe
RUN .\sqlserver-install.exe /Q /x:sqlserver-install
RUN .\sqlserver-install\SETUP.EXE /ACTION="install" /IACCEPTSQLSERVERLICENSETERMS /QUIET /INDICATEPROGRESS /INSTANCEID=MSSQLSERVER /INSTANCENAME=MSSQLSERVER

CMD ping -t localhost > NUL
