FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN curl "https://download.microsoft.com/download/B/E/D/BED73AAC-3C8A-43F5-AF4F-EB4FEA6C8F3A/ENU/x64/sqlncli.msi" -L -o sqlncli.msi
RUN msiexec /quiet /passive /qn /log sqlncli.log /i sqlncli.msi IACCEPTSQLNCLILICENSETERMS=YES ADDLOCAL=ALL

RUN curl "https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe" -L -o dotNetFx40_Full_x86_x64.exe
RUN .\dotNetFx40_Full_x86_x64.exe /install /quiet /norestart

RUN curl "https://go.microsoft.com/fwlink/?LinkID=799011" -L -o sqlserver-install.exe
RUN .\sqlserver-install.exe /ACTION="Install" /IACCEPTSQLSERVERLICENSETERMS /QUIET /VERBOSE /INDICATEPROGRESS

CMD ping -t localhost > NUL
