FROM circleci/ruby:2.5

USER root
WORKDIR /home/circleci

ADD fpm_apk_pax_header.patch /tmp
RUN apt-get update && apt-get -y install vim less build-essential rpm rpmlint lintian\
    && gem install fpm -v 1.11.0\
    && (cd /usr/local/bundle/gems/fpm-1.11.0/; patch -p 1 < /tmp/fpm_apk_pax_header.patch )\
    && rm -f /tmp/fpm_apk_pax_header.patch

USER circleci
ENTRYPOINT [ "bash" ]
