FROM circleci/php:7.1

USER root

COPY install-php7-common-dependencies.sh /tmp/install-php7-common-dependencies.sh

RUN apt-get update \
    && sh /tmp/install-php7-common-dependencies.sh \
    && apt-get install -y libmcrypt-dev \
    && pecl install mcrypt-1.0.0 \
    && docker-php-ext-enable mcrypt \
    && docker-php-ext-install pcntl \
    && docker-php-ext-enable pcntl \
    && rm -rf /var/lib/apt/lists/*

COPY php.ini /usr/local/etc/php/php.ini

USER circleci
