FROM circleci/php:5.6

USER root

RUN apt-get update \
    && apt-get install -y \
        vim \
        libssl-dev \
        libmemcached-dev \
        valgrind \
        mysql-client \
        libmcrypt-dev \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && pecl install memcached-2.2.0 \
    && docker-php-ext-enable memcached \
    && echo no | pecl install mongo-1.6.16 \
    && docker-php-ext-enable mongo \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && docker-php-ext-install mcrypt \
    && docker-php-ext-enable mysqli \
    && docker-php-ext-enable pdo \
    && docker-php-ext-enable pdo_mysql \
    && docker-php-source delete \
    && rm -rf /var/lib/apt/lists/*

USER circleci
