FROM scratch
LABEL maintainer="Agent Onboarding <team-agentonboarding@datadoghq.com>"

# The goal of this image is to be useful as a multistage docker image build
COPY start.sh /root/start.sh

CMD [ "/root/start.sh" ]
