#!/bin/bash
TMP=${DOCKER_TAG#ddtrace_centos_}
export
pwd

## Fix for a bug in Dockerhub non automated builds?
if [[ -z $DOCKERFILE_PATH ]]; then
	export DOCKERFILE_PATH=${BUILD_PATH#/*/}
fi


if [[ $TMP != $DOCKER_TAG ]]; then
	echo Build all PHP Versions
	BASE_IMAGE=${DOCKER_REPO}:ddtrace_centos
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=56 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_56 .
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=70 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_70 .
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=71 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_71 .
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=72 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_72 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=54 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_54 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=56 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_56 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=70 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_70 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=71 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_71 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=72 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_72 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=73 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_73 .
	
	echo Push all PHP Versions
	docker push ${BASE_IMAGE}_6_php_56
	docker push ${BASE_IMAGE}_6_php_70
	docker push ${BASE_IMAGE}_6_php_71
	docker push ${BASE_IMAGE}_6_php_72
	docker push ${BASE_IMAGE}_7_php_54
	docker push ${BASE_IMAGE}_7_php_56
	docker push ${BASE_IMAGE}_7_php_70
	docker push ${BASE_IMAGE}_7_php_71
	docker push ${BASE_IMAGE}_7_php_72
	docker push ${BASE_IMAGE}_7_php_73

	# This image will be buiild/pushed in normal step processing
	#   docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=54 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_54 .	
	#	docker push ${BASE_IMAGE}_6_php_54

	echo Retag upstream ZTS images
	ZTS_BASE_IMAGE=${DOCKER_REPO}:ddtrace_php_zts_
	docker tag circleci/php:5.6-zts ${ZTS_BASE_IMAGE}_56
	docker push ${ZTS_BASE_IMAGE}_56

	docker tag circleci/php:7.0-zts ${ZTS_BASE_IMAGE}_70
	docker push ${ZTS_BASE_IMAGE}_70

	docker tag circleci/php:7.1-zts ${ZTS_BASE_IMAGE}_71
	docker push ${ZTS_BASE_IMAGE}_71

	docker tag circleci/php:7.2-zts ${ZTS_BASE_IMAGE}_72
	docker push ${ZTS_BASE_IMAGE}_72

	docker tag circleci/php:7.3-zts ${ZTS_BASE_IMAGE}_73
	docker push ${ZTS_BASE_IMAGE}_73
fi

docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
