#!/bin/bash
TMP=${DOCKER_TAG#ddtrace_centos_}

## Fix for a bug in Dockerhub legacy build process
if [[ -z $DOCKERFILE_PATH ]]; then
	export DOCKERFILE_PATH=${BUILD_PATH#/*/}
fi


if [[ $TMP != $DOCKER_TAG ]]; then
	echo Build all PHP Versions
	BASE_IMAGE=${DOCKER_REPO}:ddtrace_centos
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=54 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_5_4 .
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=56 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_5_6 .
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=70 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_7_0 .
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=71 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_7_1 .
	docker build --build-arg CENTOS_VERSION=6 --build-arg PHP_VERSION=72 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_6_php_7_2 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=54 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_5_4 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=56 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_5_6 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=70 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_7_0 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=71 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_7_1 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=72 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_7_2 .
	docker build --build-arg CENTOS_VERSION=7 --build-arg PHP_VERSION=73 -f $DOCKERFILE_PATH -t ${BASE_IMAGE}_7_php_7_3 .
	
	echo Push all PHP Versions
	docker push ${BASE_IMAGE}_6_php_5_4
	docker push ${BASE_IMAGE}_6_php_5_6
	docker push ${BASE_IMAGE}_6_php_7_0
	docker push ${BASE_IMAGE}_6_php_7_1
	docker push ${BASE_IMAGE}_6_php_7_2
	docker push ${BASE_IMAGE}_7_php_5_4
	docker push ${BASE_IMAGE}_7_php_5_6
	docker push ${BASE_IMAGE}_7_php_7_0
	docker push ${BASE_IMAGE}_7_php_7_1
	docker push ${BASE_IMAGE}_7_php_7_2
	docker push ${BASE_IMAGE}_7_php_7_3

	exit 0
fi

TMP=${DOCKER_TAG#ddtrace_php_zts_}
if [[ $TMP != DOCKER_TAG ]]; then
	# Instead of building images we simply fetch source images and tag them with datadog repo and tag to ensure they only change in a controlled manner

	echo Retag upstream ZTS images
	ZTS_BASE_IMAGE=${DOCKER_REPO}:ddtrace_php_zts

	docker pull circleci/php:5.6-zts
	docker tag circleci/php:5.6-zts ${ZTS_BASE_IMAGE}_5_6
	docker push ${ZTS_BASE_IMAGE}_5_6

	docker pull circleci/php:7.0-zts
	docker tag circleci/php:7.0-zts ${ZTS_BASE_IMAGE}_7_0
	docker push ${ZTS_BASE_IMAGE}_7_0

	docker pull circleci/php:7.1-zts
	docker tag circleci/php:7.1-zts ${ZTS_BASE_IMAGE}_7_1
	docker push ${ZTS_BASE_IMAGE}_7_1

	docker pull circleci/php:7.2-zts
	docker tag circleci/php:7.2-zts ${ZTS_BASE_IMAGE}_7_2
	docker push ${ZTS_BASE_IMAGE}_7_2

	docker pull circleci/php:7.3-zts
	docker tag circleci/php:7.3-zts ${ZTS_BASE_IMAGE}_7_3
	docker push ${ZTS_BASE_IMAGE}_7_3

	exit 0
fi

# defualt build
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
